{
  parserClass="com.github.kornilova_l.matlab.MatlabParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Matlab"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.kornilova_l.matlab.psi"
  psiImplPackage="com.github.kornilova_l.matlab.psi.impl"

  elementTypeHolderClass="com.github.kornilova_l.matlab.psi.MatlabTypes"
  elementTypeClass="com.github.kornilova_l.matlab.psi.MatlabElementType"
  tokenTypeClass="com.github.kornilova_l.matlab.psi.MatlabTokenType"
}

/* The grammar simply lists all tokens */

root ::= element *
private element ::= ( newline | transpose | linecomment | float | floatexponential | identifier | integer | comment | function |
elseif | else | end | if | for | while | classdef | properties | methods | load | string | filename | openbracket |
 closebracket | lessorequal | minus | plus | dotdelete | delete | backslash | dotbackslash | dotmul | mul |
 dotpow | pow | and | matrixand | or | matrixor | dottranspose | tilda | assign | moreorequal | more | less | equal |
 notequal | coma | colon | semicolon | opensquarebracket | closesquarebracket | opencurlybracket | closecurlybracket |
 dot )
