{
  parserClass="com.github.korniloval.matlab.MatlabParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Matlab"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.korniloval.matlab.psi"
  psiImplPackage="com.github.korniloval.matlab.psi.impl"

  elementTypeHolderClass="com.github.korniloval.matlab.psi.MatlabTypes"
  elementTypeClass="com.github.korniloval.matlab.psi.MatlabElementType"
  tokenTypeClass="com.github.korniloval.matlab.psi.MatlabTokenType"
}

/* The grammar simply lists all tokens */

root ::= element *
private element ::= ( NEWLINE | TRANSPOSE | LINE_COMMENT | FLOAT | FLOAT_EXPONENTIAL | IDENTIFIER | INTEGER | COMMENT |
  FUNCTION | ELSEIF | ELSE | END | IF | FOR | WHILE | CLASSDEF | PROPERTIES | METHODS | LOAD |
  SINGLE_QUOTE_STRING | DOUBLE_QUOTE_STRING | FILE_NAME | OPEN_BRACKET | CLOSE_BRACKET | LESS_OR_EQUAL | MINUS |
  PLUS | DOT_DELETE | DELETE | BACKSLASH | DOT_BACKSLASH | DOT_MUL | MUL | DOT_POW | POW | AND | MATRIX_AND | OR |
  MATRIX_OR | DOT_TRANSPOSE | TILDA | ASSIGN | MORE_OR_EQUAL | MORE | LESS | EQUAL | NOT_EQUAL | COMA | COLON | SEMICOLON |
  OPEN_SQUARE_BRACKET | CLOSE_SQUARE_BRACKET | OPEN_CURLY_BRACKET | CLOSE_CURLY_BRACKET | DOT )
